### ISSUE TITLE
History Tab content

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-io-typescript#51]
https://typescript.giveth.io/about
History tab needs more content

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/f299210d-1cc5-4662-8163-df51e9f9b5e8)

**Comment by laurenluz** [comment]
Hey @MoeNick, looking at this page... the "About Us" text blurb (also missing content) is really not needed... everything is covered in the part above and the mission/vision part below... This would just be some kind of fluff we'd need to make up

![image](https://user-images.githubusercontent.com/75490971/151890618-4cd8b1ff-49c1-4ae7-be82-8bab4625e494.png)

As for the History....

![image](https://user-images.githubusercontent.com/75490971/151890679-b26727ce-3169-4a3e-a790-7660dee27393.png)
should say: "Giveth was founded in 2016 and provided value to the Blockchain4Good ecosystem for 5 years, funded solely by donations."
 
![image](https://user-images.githubusercontent.com/75490971/151891117-52e58ce8-0304-4073-8722-78fd91beacf3.png)
should say: "The launch of the GIVeconomy in December 2021 provided a new way to fund our initiatives to evolve philanthropy."

also can we make the highlighted blurb stylized w a nice background too?

Will write content for the last part in a bit...

**Comment by laurenluz** [comment]
So since there are three parts...

**Rising out of the ashes of TheDAO**
The Giveth founding team was a group of altruistic whitehat hackers who set out to build systems to turn non-profits into DAOs of their own, starting with platforms for P2P giving on the blockchain.

**Starting with traceable donations"
After writing and open-sourcing innovative smart contracts like the MiniMe token, the team launched the first Giveth DApp, now called Giveth TRACE, to enable a traceable & accountable donations to for-good Campaigns.

**And now... the GIVeconomy"
Building on that foundation and heaven-bent on using blockchain to fund public goods regeneratively, we created the GIVeconomy. Fueled by GIV, the GIVeconomy is rewarding & empowering all who give.

Then I think there should be a last page (a fourth part?) or another section that has a button link... so it says:
"Take a dive into the History of Giveth"
Button "Read More"
which links to: https://docs.giveth.io/whatisgiveth/history/

@MoeNick @markoprljic - sound good?

**Comment by MoeNick** [comment]
@mosaeedi can you see how we can have the content from Lauren implemented in the design? can you confirm pls?
